services:
  bot:
    build: .
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: media_downloader
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
